name: Simple FastApi Shenanigans

on:
    push:
        branches:
            - main
            - dev

env:
    MYSQL_DATABASE: somedb
    MYSQL_PASSWORD: Password1!
    MYSQL_USER: root

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Retrieve Code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: pip install -r requirements.txt