name: Simple FastApi Shenanigans

on:
    push:
        branches:
            - main
            - dev

env:
    MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
    MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    MYSQL_USER: ${{ secrets.MYSQL_USER }}

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Retrieve Code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run: pip install -r requirements.txt